.clang-format

[feat]: #16 create .clang-format file

---

client.cpp
include/User.hpp
src/User.cpp

[refactor]: #61 refactor for linux compilation

---

include/Command.hpp
include/Error.hpp
include/User.hpp
src/Command.cpp
src/Error.cpp
src/User.cpp

[body]
make error class
change error message in Command.cpp
[notes]

[feat]: #44 make error class

---

Makefile
docker-compose.yml

[body]
add make command
[notes]
close #73

[feat]: #73 add make command

---

include/Channel.hpp
src/Channel.cpp

[body]
add ChannelMode
[notes]
close #64

[feat]: #64 add ChannelMode

---

src/Command.cpp
src/Command_PASS.cpp

[type]: #75 separate PASS command implementation into own file

---

Makefile
include/Channel.hpp
include/Command.hpp
include/Server.hpp
include/User.hpp
src/Channel.cpp
src/Command.cpp
src/Command_JOIN.cpp
src/Command_PASS.cpp
src/Command_USER.cpp
src/Error.cpp
src/Server.cpp
src/User.cpp

- "JOIN #ch1,#ch2 key1,key2"のように複数のチャンネルかパスワードを設定する場合にはカンマ区切りにするように修正しました
- Makefileに"make nc"でncコマンドが実行できるルールを追加しました

91 feat join commas, 94 feat make nc

---

include/Error.hpp
src/Command_NICK.cpp
src/Error.cpp

[body]
add error message (ERR_TOOMANYPARAMS)
[notes]
close #115

[bug]: #115 add error message

---

include/Channel.hpp
include/Command.hpp
src/Channel.cpp
src/Command.cpp
src/Command_MODE.cpp

- MODEコマンドのkモードを実装しました
- チャンネルオペレーターであれば、そのチャンネルのパスワードを確認、変更、削除することができます

70 feat mode k

---

include/Channel.hpp
include/Command.hpp
include/Error.hpp
src/Channel.cpp
src/Command.cpp
src/Command_JOIN.cpp
src/Command_MODE.cpp
src/Error.cpp

- MODEコマンドのlフラグを実装しました
- MODEコマンドのlフラグでチャンネルのユーザー数を制限した場合、JOINコマンドを使っても弾けるようにしました

98 feat mode l

---

include/Channel.hpp
include/Command.hpp
include/Reply.hpp
include/Server.hpp
src/Channel.cpp
src/Command.cpp
src/Command_INVITE.cpp
src/Command_JOIN.cpp
src/Command_MODE.cpp
src/Command_QUIT.cpp
src/Command_USER.cpp
src/Reply.cpp
src/Server.cpp

[feat]: #41 implement simplified QUIT

---

include/Command.hpp
include/Server.hpp
src/Command.cpp
src/Command_PRIVMSG.cpp
src/Server.cpp

[body]
プライベートメッセージを送信できる関数を作成いたしました。
\~使用方法\~
二名以上のクライアントで接続
`PRIVMSG [channel name or client nick name] :message`
close #45

[feat]: #45 PRIVMSG command

---

include/Command.hpp
include/Reply.hpp
include/Server.hpp
include/User.hpp
src/Command.cpp
src/Command_KILL.cpp
src/Command_MODE.cpp
src/Command_OPER.cpp
src/Reply.cpp
src/Server.cpp
src/User.cpp

- Operコマンドを作成しました
- Operコマンドに必要なパスワードはServerのコンストラクタで"password"と設定しています
- Modeコマンドの-oフラグをユーザーに対しても行えるようにしました
- Killコマンドを作成しました
- IRCオペレーターであれば指定したユーザーを消すことができます
- Killコマンドの引数には必ずコメント必要で、それを見た人が満足するような適切な理由を提供する必要があるそうです

47 feat OPER command, 124 feat KILL command

---

src/Reply.cpp

[feat]: #149 nullptr ->NULL

---

src/Command_NICK.cpp
src/Command_PART.cpp
src/Command_PASS.cpp
src/Command_PRIVMSG.cpp
src/Command_USER.cpp
src/Reply.cpp
src/Server.cpp

[body]
PRIVMSGのバグを修正しました。
具体的には、:が先頭についたり、welcomメッセージのスペルミスがあったり
[notes]

[fix]: #152 fix PRIVMSG bug

---

src/Command.cpp

[feat]: #154 exec KILL command when receiving "kill"

---

client.cpp
include/Command.hpp
src/Command.cpp
src/Command_JOIN.cpp
src/Command_KICK.cpp
src/Command_QUIT.cpp

[type]: #54 implement KICK

---

include/Server.hpp
src/Command_JOIN.cpp
src/Command_MODE.cpp
src/Command_PART.cpp
src/Command_QUIT.cpp
src/Command_TOPIC.cpp
src/Server.cpp

[body]
sendTochannelUserの関数名を変更した
[notes]

[feat]: #160 privmsg sendTochannelUser

---

src/Command_NICK.cpp

[body]
ニックコマンドを何回でも使用できるように変更した
[notes]

[fix]: #163 change nick command

---

config.conf
src/Command.cpp
src/Command_JOIN.cpp
src/Command_KILL.cpp
src/Command_MODE.cpp
src/Command_NICK.cpp
src/Command_PART.cpp
src/Command_PASS.cpp
src/Command_PRIVMSG.cpp
src/Command_TOPIC.cpp
src/Command_USER.cpp
src/Server.cpp
src/User.cpp

[refactor]: #164 add alias in config.conf and comment out debug message

---

src/Command_NICK.cpp
src/Reply.cpp

nickコマンドで弾かれるべきでない名前([]\\{})が弾かれていた

170 bug nick name
